//! The [`CommitDelta`] captures everything that changed in a single committed
//! transaction. It is the unit of replication: the Primary publishes deltas to
//! a distributed log, and Replicas consume them to update their local state.
//!
//! This module also defines the [`DistributedLog`] trait — the abstraction over
//! whatever transport carries deltas between nodes.

use std::sync::Arc;

use async_trait::async_trait;
use common::{
    persistence::{
        DocumentLogEntry,
        PersistenceIndexEntry,
    },
    types::Timestamp,
};
use futures::stream::BoxStream;

use crate::write_log::WriteSource;

/// Everything that changed in a single committed transaction.
///
/// Produced by the Committer after a successful commit. Contains enough
/// information for a Replica to:
/// 1. Update its [`SnapshotManager`] (via the document and index writes)
/// 2. Append to its local [`WriteLog`] (for subscription invalidation)
/// 3. Maintain ordering (via the commit timestamp)
#[derive(Clone, Debug)]
pub struct CommitDelta {
    /// The commit timestamp assigned by the Committer.
    pub ts: Timestamp,

    /// Document writes (inserts, updates, deletes) persisted in this commit.
    pub document_writes: Arc<Vec<DocumentLogEntry>>,

    /// Index updates generated by this commit.
    pub index_writes: Arc<Vec<PersistenceIndexEntry>>,

    /// The source of the write (e.g. which mutation function triggered it).
    pub write_source: WriteSource,

    /// Total bytes written to persistence.
    pub write_bytes: u64,
}

/// Abstraction over the transport that carries [`CommitDelta`]s between
/// the Primary node and Replica nodes.
///
/// The Primary calls [`publish`] after each commit. Replicas call [`subscribe`]
/// to get an ordered stream of deltas starting from a given timestamp.
#[async_trait]
pub trait DistributedLog: Send + Sync + 'static {
    /// Publish a committed delta to the log.
    ///
    /// Must be durable: once this returns Ok, Replicas are guaranteed to
    /// eventually see this delta.
    async fn publish(&self, delta: CommitDelta) -> anyhow::Result<()>;

    /// Subscribe to deltas starting after `from_ts`. Returns an ordered stream
    /// that blocks when caught up, resuming when new deltas arrive.
    async fn subscribe(
        &self,
        from_ts: Timestamp,
    ) -> anyhow::Result<BoxStream<'static, anyhow::Result<CommitDelta>>>;
}

/// No-op implementation for single-node deployments. `publish` does nothing,
/// `subscribe` returns a stream that never yields.
pub struct NoopDistributedLog;

#[async_trait]
impl DistributedLog for NoopDistributedLog {
    async fn publish(&self, _delta: CommitDelta) -> anyhow::Result<()> {
        Ok(())
    }

    async fn subscribe(
        &self,
        _from_ts: Timestamp,
    ) -> anyhow::Result<BoxStream<'static, anyhow::Result<CommitDelta>>> {
        Ok(Box::pin(futures::stream::pending()))
    }
}

#[cfg(any(test, feature = "testing"))]
pub mod testing {
    use std::sync::Arc;

    use async_trait::async_trait;
    use common::types::Timestamp;
    use futures::stream::BoxStream;
    use parking_lot::Mutex;
    use tokio::sync::broadcast;
    use tokio_stream::wrappers::BroadcastStream;
    use tokio_stream::StreamExt;

    use super::{
        CommitDelta,
        DistributedLog,
    };

    /// In-memory [`DistributedLog`] for testing. Stores deltas in a Vec and
    /// notifies subscribers via a broadcast channel.
    pub struct InMemoryDistributedLog {
        deltas: Arc<Mutex<Vec<CommitDelta>>>,
        sender: broadcast::Sender<CommitDelta>,
    }

    impl InMemoryDistributedLog {
        pub fn new() -> Self {
            let (sender, _) = broadcast::channel(4096);
            Self {
                deltas: Arc::new(Mutex::new(Vec::new())),
                sender,
            }
        }

        /// Returns all deltas published so far.
        pub fn deltas(&self) -> Vec<CommitDelta> {
            self.deltas.lock().clone()
        }
    }

    #[async_trait]
    impl DistributedLog for InMemoryDistributedLog {
        async fn publish(&self, delta: CommitDelta) -> anyhow::Result<()> {
            self.deltas.lock().push(delta.clone());
            let _ = self.sender.send(delta);
            Ok(())
        }

        async fn subscribe(
            &self,
            from_ts: Timestamp,
        ) -> anyhow::Result<BoxStream<'static, anyhow::Result<CommitDelta>>> {
            let existing: Vec<CommitDelta> = self
                .deltas
                .lock()
                .iter()
                .filter(|d| d.ts > from_ts)
                .cloned()
                .collect();

            let receiver = self.sender.subscribe();
            let broadcast_stream = BroadcastStream::new(receiver)
                .filter_map(move |result| match result {
                    Ok(delta) if delta.ts > from_ts => Some(Ok(delta)),
                    Ok(_) => None,
                    Err(e) => Some(Err(anyhow::anyhow!("broadcast lag: {e}"))),
                });

            let existing_stream = futures::stream::iter(existing.into_iter().map(Ok));
            let combined = existing_stream.chain(broadcast_stream);
            Ok(Box::pin(combined))
        }
    }
}
